import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const LISTINGS=["https://traded.co/deals/new-york/multifamily/sale/","https://traded.co/deals/new-york/office/sale/","https://traded.co/deals/new-york/retail/sale/","https://traded.co/deals/new-york/industrial/sale/","https://traded.co/deals/new-york/hotel/sale/","https://traded.co/deals/new-york/mixed-use/sale/","https://traded.co/deals/new-york/development/sale/","https://traded.co/deals/new-york/","https://traded.co/deals/manhattan/","https://traded.co/deals/brooklyn/","https://traded.co/deals/queens/","https://traded.co/deals/bronx/"];
const SITEMAP="https://traded.co/sitemap.xml",DEADLINE_MS=13*60_000,CONCURRENCY=4;
const ASSET:Record<string,string>={multifamily:"Multifamily",office:"Office",retail:"Retail",industrial:"Industrial",hotel:"Hotel","mixed-use":"Mixed-Use",development:"Development Site","development-site":"Development Site"};
const BOROUGH:Array<[RegExp,string]>=[[/\bstaten island\b/i,"Staten Island"],[/\bbrooklyn\b/i,"Brooklyn"],[/\bqueens\b/i,"Queens"],[/\bbronx\b/i,"Bronx"],[/\bmanhattan\b/i,"Manhattan"],[/\bwilliamsburg|bushwick|dumbo|park slope|bed-stuy|bedford-stuyvesant|sunset park\b/i,"Brooklyn"],[/\bastoria|long island city|flushing|jamaica|sunnyside\b/i,"Queens"],[/\bmott haven|fordham|riverdale\b/i,"Bronx"],[/\bharlem|tribeca|soho|chelsea|midtown|upper east side|upper west side|inwood|hudson yards\b/i,"Manhattan"]];
const supa=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
const slug=(u:string)=>(u.split("/").filter(Boolean).pop()||"deal").toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-+|-+$/g,"");
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim()||null;
const pick=(o:any,keys:string[])=>{for(const k of keys)if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!=="")return o[k];return null;};
const saleDate=(v:unknown)=>{const s=String(v??"").trim();if(!s)return null;if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10);};
function urlNorm(v:unknown){try{const raw=String(v??"").trim(),u=new URL(raw.startsWith("/")?`https://traded.co${raw}`:raw);if(!/(^|\.)traded\.co$/i.test(u.hostname)||!/^\/deals\/new-york\/[a-z-]+\/sale\/[^/]+\/?$/i.test(u.pathname))return null;return`https://traded.co${u.pathname.replace(/\/+$/,"/")}`;}catch{return null;}}
function nextData(html:string){const m=html.match(/<script id="__NEXT_DATA__" type="application\/json">([\s\S]*?)<\/script>/);if(!m)return null;try{return JSON.parse(m[1]);}catch{return null;}}
function dealObject(root:any){let found:any=null;(function walk(o:any){if(found||!o||typeof o!=="object")return;if(!Array.isArray(o)&&Array.isArray(o.properties)&&(o.salePrice!==undefined||o.closingDate!==undefined)){found=o;return;}for(const k of Object.keys(o))walk(o[k]);})(root);return found;}
function party(deal:any,role:"buyer"|"seller"){const group=role==="buyer"?deal?.buyers:deal?.sellers,arr=group&&(group.profileDealCompanies||group.edges);if(Array.isArray(arr)){const hit=arr.find((x:any)=>(x.role||x.node?.role)===role)||arr[0];return clean(hit?.profile?.name||hit?.node?.profile?.name||hit?.node?.name);}return null;}
function titleParties(title:string){const m=title.match(/\b(acquires?|buys?|purchases?|sells?)\b/i);if(!m)return{buyer:null,seller:null};const lead=clean(title.slice(0,m.index));let rest=title.slice((m.index||0)+m[0].length);const cut=rest.search(/\s+\b(?:for|in|at|with|represented)\b/i);if(cut>=0)rest=rest.slice(0,cut);if(/^sells?$/i.test(m[1]))return{seller:lead,buyer:clean(rest.replace(/^\s*to\s+/i,""))};return{buyer:lead,seller:clean(rest.replace(/^\s*from\s+/i,""))};}
function borough(text:string,zip:unknown){const z=String(zip??"").match(/^\d{5}/)?.[0];if(z){const n=Number(z),p=Math.floor(n/100);if(n===11004||n===11005||[111,113,114,116].includes(p))return"Queens";if([100,101,102].includes(p))return"Manhattan";if(p===103)return"Staten Island";if(p===104)return"Bronx";if(p===112)return"Brooklyn";}for(const[re,b]of BOROUGH)if(re.test(text))return b;return null;}
function asset(url:string,deal:any){const structured=clean(pick(deal,["assetType","asset_type"]));if(structured)return structured;const m=url.match(/\/(multifamily|office|retail|industrial|hotel|mixed-use|development|development-site)\//i);return m?ASSET[m[1].toLowerCase()]||null:null;}
function mapDeal(deal:any,url:string){if(!deal)return null;const prop=Array.isArray(deal.properties)?deal.properties[0]||{}:{},address=clean(pick(prop,["displayAddress","address","fullAddress","name"]));if(!address)return null;const title=String(pick(deal,["title","articleTitle","caption"])||""),fallback=titleParties(title),structuredBuyer=party(deal,"buyer"),structuredSeller=party(deal,"seller"),buyer=structuredBuyer||fallback.buyer,seller=structuredSeller||fallback.seller,price=Number(pick(deal,["salePrice","sale_price","amount","price"])||0),sqft=Number(pick(deal,["totalSquareFootageDeal","squareFeet","square_feet"])||0),date=saleDate(pick(deal,["closingDate","closing_date"])),b=borough([prop.submarket,title,address].filter(Boolean).join(" "),prop.zip);let confidence=20+(price>0?25:0)+(buyer?20:0)+(seller?15:0)+(date?10:0);const heuristic=(buyer&&!structuredBuyer)||(seller&&!structuredSeller);return{shortcode:`TRADED-${slug(url)}`,address,borough:b,market:b?b.toLowerCase():null,asset_type:asset(url,deal),sale_price:price>0?price:null,units:null,sqft:sqft>0?sqft:null,sale_date:date,post_date:new Date().toISOString(),source_system:"traded",source_url:url,confidence:Math.min(100,confidence),parse_status:confidence>=60&&!heuristic?"ok":"needs_review",verification_status:"unverified",record_quality:"ok",notes:`Traded.co closed-sale feed | ${url}`,buyer,seller,provenance:{source:"traded",structured_parties:Boolean(structuredBuyer||structuredSeller),title}};}
async function scraper(key:string,url:string){const r=await fetch(`https://api.scraperapi.com/?api_key=${encodeURIComponent(key)}&url=${encodeURIComponent(url)}&country_code=us`,{headers:{accept:"text/html,*/*"}});if(!r.ok)throw new Error(`ScraperAPI ${r.status} for ${url}`);const t=await r.text();if(/cloudflare|captcha|access denied/i.test(t.slice(0,5000)))throw new Error(`challenge body for ${url}`);return t;}
async function pool<T,R>(items:T[],n:number,fn:(x:T)=>Promise<R>){const out:R[]=[];let i=0;async function worker(){while(i<items.length){const x=items[i++];try{out.push(await fn(x));}catch(e){console.log(String(e));}}}await Promise.all(Array.from({length:Math.min(n,items.length)},worker));return out;}
async function ledgerFresh(urls:string[]){if(!urls.length)return[];const{data,error}=await supa.from("sbi_fetch_ledger").select("source_key,disposition").eq("source","traded").in("source_key",urls);if(error)throw error;const done=new Set((data||[]).filter((r:any)=>!String(r.disposition).startsWith("fetch_error:")).map((r:any)=>r.source_key));return urls.filter(u=>!done.has(u));}
async function mark(url:string,disposition:string){await supa.from("sbi_fetch_ledger").upsert({source:"traded",source_key:url,disposition,fetched_at:new Date().toISOString()},{onConflict:"source,source_key"});}
async function discover(key:string){const found=new Set<string>();for(const html of await pool(LISTINGS,CONCURRENCY,u=>scraper(key,u))){const root=nextData(html);(function walk(o:any){if(!o||typeof o!=="object")return;if(typeof o.url==="string"){const n=urlNorm(o.url);if(n)found.add(n);}for(const k of Object.keys(o))walk(o[k]);})(root);}try{const idx=await scraper(key,SITEMAP),sub=[...idx.matchAll(/<loc>([^<]+\.xml)<\/loc>/g)].map(m=>m[1]).filter(x=>/deal|post|sitemap/i.test(x)).slice(0,30);for(const xml of await pool(sub,CONCURRENCY,u=>scraper(key,u)))for(const m of xml.matchAll(/<loc>(https:\/\/traded\.co\/deals\/new-york\/[a-z-]+\/sale\/[^<]+)<\/loc>/g)){const n=urlNorm(m[1]);if(n)found.add(n);}}catch(e){console.log("sitemap optional",String(e));}return[...found];}
async function run(req:Request){const key=req.headers.get("x-scraperapi-key")||"";if(!key)return json({ok:false,error:"SCRAPERAPI_KEY is not configured on the server-side orchestrator"},400);let body:any={};try{body=await req.json();}catch{}const max=Math.max(1,Math.min(200,Number(body.max_fetches||body.maxFetches||50))),started=Date.now();let runId=body.run_id||null;if(!runId){const{data}=await supa.from("sbi_source_runs").insert({source:"traded",job:"traded_refresh",status:"running",stats:{stage:"discovery"}}).select("run_id").single();runId=data?.run_id;}else await supa.from("sbi_source_runs").update({status:"running",started_at:new Date().toISOString(),stats:{stage:"discovery"}}).eq("run_id",runId);try{const discovered=await discover(key),fresh=await ledgerFresh(discovered),batch=fresh.slice(0,max),deals:any[]=[];let fetchErrors=0;for(const u of batch){if(Date.now()-started>DEADLINE_MS)break;try{const html=await scraper(key,u),d=mapDeal(dealObject(nextData(html)),u);if(d){deals.push(d);await mark(u,"processed");}else await mark(u,"no_parse");}catch(e){fetchErrors++;await mark(u,`fetch_error:${String(e).slice(0,120)}`);}}const{data,error}=deals.length?await supa.rpc("sync_upsert_deals",{rows:deals}):{data:{inserted:0,dup:0,errors:0},error:null};if(error)throw error;const status=fetchErrors||Number(data?.errors||0)?"completed_with_errors":"completed",stats={discovered:discovered.length,fresh:fresh.length,fetched:batch.length,parsed:deals.length,fetch_errors:fetchErrors,...data,remaining:Math.max(0,fresh.length-batch.length),elapsed_ms:Date.now()-started};if(runId)await supa.from("sbi_source_runs").update({status,finished_at:new Date().toISOString(),stats,error:status==="completed"?null:`${fetchErrors} fetch errors`}).eq("run_id",runId);return json({ok:status==="completed",run_id:runId,status,stats});}catch(e){if(runId)await supa.from("sbi_source_runs").update({status:"failed",finished_at:new Date().toISOString(),error:String(e)}).eq("run_id",runId);return json({ok:false,run_id:runId,error:String(e)},500);}}
Deno.serve(run);
