import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const supa=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const URL="https://data.cityofnewyork.us/resource/usep-8jbt.json";
const BC:Record<string,string>={Manhattan:"1",Bronx:"2",Brooklyn:"3",Queens:"4","Staten Island":"5"};
const SUF:Record<string,string>={STREET:"ST",ST:"ST",AVENUE:"AVE",AVE:"AVE",BOULEVARD:"BLVD",BLVD:"BLVD",ROAD:"RD",RD:"RD",DRIVE:"DR",DR:"DR",LANE:"LN",LN:"LN",COURT:"CT",CT:"CT",PLACE:"PL",PL:"PL",PARKWAY:"PKWY",PKWY:"PKWY",HIGHWAY:"HWY",HWY:"HWY",TERRACE:"TER",TER:"TER"};
const DIR:Record<string,string>={EAST:"E",WEST:"W",NORTH:"N",SOUTH:"S"};
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
function canon(s:unknown){return String(s??"").toUpperCase().replace(/[.,#]/g," ").replace(/\b(\d+)(ST|ND|RD|TH)\b/g,"$1").split(/\s+/).filter(Boolean).map(t=>DIR[t]||SUF[t]||t).join(" ");}
function split(a:string){const m=String(a||"").toUpperCase().match(/^\s*([0-9]+(?:-[0-9]+)?)\s+(.+?)(?:\s+(?:MANHATTAN|BROOKLYN|QUEENS|BRONX|STATEN ISLAND)(?:\s+NY)?)?\s*$/);return m?[m[1],canon(m[2])]:[null,null];}
function consistent(values:unknown[]){const s=new Set<number>();for(const v of values){const n=Number(v);if(Number.isFinite(n)&&n>0)s.add(Math.trunc(n));}return s.size===1?[...s][0]:null;}
async function fetchRows(address:string,borough:string){const[num,name]=split(address);if(!num||!name||!BC[borough])return[];const toks=String(name).split(" ").filter(x=>x.length>2);if(!toks.length)return[];const tok=toks.sort((a,b)=>b.length-a.length)[0].replace(/'/g,"''"),n=String(num).replace(/'/g,"''");const q=new URLSearchParams({"$select":"address,gross_square_feet,total_units,building_class_at_time_of,sale_price","$where":`borough='${BC[borough]}' AND address like '${n} %${tok}%'`,"$limit":"50"});const r=await fetch(`${URL}?${q}`,{headers:{"user-agent":"Skyline-SBI-Rolling/1.0"}});if(!r.ok)throw new Error(`Rolling Sales ${r.status}`);const rows=await r.json();return rows.filter((x:any)=>canon(String(x.address||"").replace(/^\S+\s+/,""))===name&&!String(x.building_class_at_time_of||"").toUpperCase().startsWith("R"));}
Deno.serve(async(req:Request)=>{let body:any={};try{body=await req.json();}catch{}const limit=Math.max(1,Math.min(1000,Number(body.limit||400)));let runId=body.run_id||null;const stats={targets:0,sqft_filled:0,units_filled:0,conflict_flagged:0,ambiguous:0,nohit:0,fetch_errors:0};try{if(!runId){const{data}=await supa.from("sbi_source_runs").insert({source:"nyc_rolling_sales",job:"rolling_sales",status:"running"}).select("run_id").single();runId=data?.run_id;}else await supa.from("sbi_source_runs").update({status:"running",started_at:new Date().toISOString()}).eq("run_id",runId);const{data:targets,error}=await supa.rpc("sbi_rolling_targets",{lim:limit});if(error)throw error;stats.targets=(targets||[]).length;for(const t of targets||[]){try{const rows=await fetchRows(t.address_raw,t.borough);if(!rows.length){stats.nohit++;await supa.rpc("sbi_rolling_apply",{p_deal_id:t.deal_id,p_sqft:null,p_units:null,p_source_rows:[]});continue;}const sf=consistent(rows.map((x:any)=>x.gross_square_feet)),un=consistent(rows.map((x:any)=>x.total_units));if(sf===null&&un===null)stats.ambiguous++;const{data:r,error:e}=await supa.rpc("sbi_rolling_apply",{p_deal_id:t.deal_id,p_sqft:sf,p_units:un,p_source_rows:rows});if(e)throw e;const filled=r?.filled||[],conflicts=r?.conflicts||[];if(filled.includes("sqft"))stats.sqft_filled++;if(filled.includes("units"))stats.units_filled++;stats.conflict_flagged+=conflicts.length;}catch(e){stats.fetch_errors++;console.log(String(e));}}const status=stats.fetch_errors?"completed_with_errors":"completed";await supa.from("sbi_source_runs").update({status,finished_at:new Date().toISOString(),stats,error:stats.fetch_errors?`${stats.fetch_errors} fetch errors`:null}).eq("run_id",runId);return json({ok:status==="completed",run_id:runId,status,stats});}catch(e){if(runId)await supa.from("sbi_source_runs").update({status:"failed",finished_at:new Date().toISOString(),error:String(e),stats}).eq("run_id",runId);return json({ok:false,run_id:runId,error:String(e),stats},500);}});
