import type { Config } from "@netlify/functions";

type Row = Record<string, any>;
const RAW_CSV = "https://raw.githubusercontent.com/rubbik26-commits/buyerDB/ACRIS/skyline/NEW_YORK_CLOSED_ENRICHED_v8.csv";
const VALID_BOROUGHS = new Set(["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]);
const env = (name: string) => (globalThis as any).Netlify?.env?.get?.(name) || "";
const json = (data: unknown, status = 200) => new Response(JSON.stringify(data, null, 2), { status, headers: { "content-type": "application/json" } });
const pathOf = (req: Request) => new URL(req.url).pathname.replace(/\/$/, "") || "/";
const qs = (req: Request) => new URL(req.url).searchParams;
const money = (v: unknown) => { if (v === null || v === undefined || v === "") return null; const n = Number(String(v).replace(/[$,\s]/g, "")); return Number.isFinite(n) ? n : null; };
const norm = (s: unknown) => String(s || "").trim().toUpperCase().replace(/[^A-Z0-9]+/g, " ").replace(/\s+/g, " ").trim();
const safeId = (prefix: string, s: unknown) => `${prefix}-${norm(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "unknown"}`;
const T = { deals: "sbi_deals", properties: "sbi_properties", parties: "sbi_deal_parties", entities: "sbi_entities", contacts: "sbi_contacts", review: "sbi_review_queue" };
function cfg() { const raw = env("SUPABASE_URL") || env("VITE_SUPABASE_URL") || env("VITE_API_URL"); const key = env("SUPABASE_SERVICE_ROLE_KEY") || env("SUPABASE_SERVICE_KEY") || env("SUPABASE_PUBLISHABLE_KEY") || env("VITE_SUPABASE_ANON_KEY"); if (!raw || !key) throw new Error("Supabase URL/key env vars are missing."); return { url: new URL(raw).origin, key }; }
async function rest(route: string, init: RequestInit = {}) { const c = cfg(); const headers = new Headers(init.headers || {}); headers.set("apikey", c.key); headers.set("authorization", `Bearer ${c.key}`); if (init.body && !headers.has("content-type")) headers.set("content-type", "application/json"); const r = await fetch(`${c.url}/rest/v1/${route}`, { ...init, headers }); if (!r.ok) throw new Error(`${route} ${r.status}: ${(await r.text()).slice(0, 500)}`); return r.status === 204 ? null : r.json(); }
const sel = (table: string, query = "select=*") => rest(`${table}?${query}`);
const maybe = async (table: string, query = "select=*") => { try { return await sel(table, query); } catch { return []; } };
const patch = (route: string, body: unknown) => rest(route, { method: "PATCH", headers: { prefer: "return=representation" }, body: JSON.stringify(body) });

function parseCsv(text: string): Row[] { const rows: string[][] = []; let row: string[] = [], cur = "", q = false; for (let i = 0; i < text.length; i++) { const ch = text[i], next = text[i + 1]; if (q) { if (ch === '"' && next === '"') { cur += '"'; i++; } else if (ch === '"') q = false; else cur += ch; } else if (ch === '"') q = true; else if (ch === ",") { row.push(cur); cur = ""; } else if (ch === "\n") { row.push(cur); rows.push(row); row = []; cur = ""; } else if (ch !== "\r") cur += ch; } if (cur || row.length) { row.push(cur); rows.push(row); } const headers = (rows.shift() || []).map((h) => h.trim()); return rows.filter((r) => r.some(Boolean)).map((r) => Object.fromEntries(headers.map((h, i) => [h, r[i] || ""]))); }
function srcSystem(url: string) { const u = String(url || "").toLowerCase(); if (u.includes("a836-acris")) return "acris"; if (u.includes("traded.co")) return "traded"; if (u.includes("crexi")) return "crexi"; if (u.includes("instagram")) return "instagram"; return "csv"; }
async function loadCsv() { const res = await fetch(RAW_CSV, { headers: { "user-agent": "buyerdb-core-fallback" } }); if (!res.ok) throw new Error(`CSV fallback fetch failed ${res.status}`); const rows = parseCsv(await res.text()).filter((r) => VALID_BOROUGHS.has(String(r.Borough || ""))); const ent = new Map<string, Row>(); const properties: Row[] = [], deals: Row[] = [], parties: Row[] = [], reviews: Row[] = []; const contacts: Row[] = [], contactsByEntity = new Map<string, Row[]>(); const propSeen = new Set<string>(); const addEnt = (name: string) => { if (!name || !String(name).trim()) return null; const entity_id = safeId("ent", name); if (!ent.has(entity_id)) ent.set(entity_id, { entity_id, display_name: String(name).trim(), entity_type: /\bLLC\b/i.test(name) ? "llc" : "unknown", is_spv_suspect: false }); return ent.get(entity_id)!; };
  rows.forEach((r, i) => { const address = String(r.Address || "").trim(); const borough = String(r.Borough || "").trim(); if (!address || !borough) return; const property_id = safeId("prop", `${address}-${borough}`); if (!propSeen.has(property_id)) { propSeen.add(property_id); properties.push({ property_id, address_raw: address, borough, market: r.Market || null, latitude: null, longitude: null, bbl: null }); } const deal_id = safeId("deal", r.Shortcode || `${address}-${r["Sale Price"]}-${r.sale_date_iso || r["Sale Date"]}-${i}`); const buyer = addEnt(r.Buyer); const seller = addEnt(r.Seller); const sale_price = money(r["Sale Price"]); const units = money(r.Units); const sqft = money(r["Sq Ft"]); const d: Row = { deal_id, property_id, sale_date: r.sale_date_iso || r["Sale Date"] || null, post_date: r["Post Date"] || null, asset_type: r["Asset Type"] || null, sale_price, units, sqft, ppu: money(r.PPU), ppsf: money(r.PPSF), source_system: srcSystem(r["Source URL"]), source_url: r["Source URL"] || null, shortcode: r.Shortcode || null, confidence: money(r.Confidence), parse_status: r["Parse Status"] || "ok", notes: r.Notes || null, property: properties.find((p) => p.property_id === property_id) || {}, buyers: buyer ? [buyer] : [], sellers: seller ? [seller] : [] }; deals.push(d); if (buyer) parties.push({ deal_id, entity_id: buyer.entity_id, role: "buyer", source_system: d.source_system }); if (seller) parties.push({ deal_id, entity_id: seller.entity_id, role: "seller", source_system: d.source_system }); if (d.parse_status === "needs_review") reviews.push({ review_id: `csv-review-${deal_id}`, object_type: "deal", object_id: deal_id, issue_class: "legacy_needs_review", severity: "normal", payload: { address, notes: d.notes }, status: "open" }); });
  const entities = Array.from(ent.values()); return { deals, properties, parties, entities, contacts, reviews, ent, contactsByEntity, source: "csv-fallback" }; }
async function loadSupa() { const [deals, properties, parties, entities, contacts, reviews] = await Promise.all([sel(T.deals, "select=*&order=sale_date.desc.nullslast&limit=5000"), sel(T.properties, "select=*&limit=5000"), sel(T.parties, "select=*&limit=12000"), sel(T.entities, "select=*&limit=12000"), maybe(T.contacts, "select=*&limit=12000"), maybe(T.review, "select=*&status=eq.open&order=created_at.desc&limit=1000")]); const prop = new Map(properties.map((p: Row) => [p.property_id, p])); const ent = new Map(entities.map((e: Row) => [e.entity_id, e])); const byDeal = new Map<string, Row[]>(); for (const p of parties) { if (!byDeal.has(p.deal_id)) byDeal.set(p.deal_id, []); byDeal.get(p.deal_id)!.push(p); } const contactsByEntity = new Map<string, Row[]>(); for (const c of contacts) { if (!contactsByEntity.has(c.entity_id)) contactsByEntity.set(c.entity_id, []); contactsByEntity.get(c.entity_id)!.push(c); } const rows = deals.map((d: Row) => { const ps = byDeal.get(d.deal_id) || []; return { ...d, property: prop.get(d.property_id) || {}, parties: ps, buyers: ps.filter((p) => p.role === "buyer").map((p) => ent.get(p.entity_id)).filter(Boolean), sellers: ps.filter((p) => p.role === "seller").map((p) => ent.get(p.entity_id)).filter(Boolean) }; }); return { deals: rows, properties, parties, entities, contacts, reviews, ent, contactsByEntity, source: "supabase" }; }
async function load() { try { const data = await loadSupa(); if (data.deals.length) return data; return await loadCsv(); } catch { return await loadCsv(); } }
function dealOut(d: Row) { const b = (d.buyers || [])[0], s = (d.sellers || [])[0]; return { property_id: d.property_id, deal_id: d.deal_id, sale_date: d.sale_date, address: d.property?.address_raw, borough: d.property?.borough, market: d.property?.market, bbl: d.property?.bbl, latitude: d.property?.latitude, longitude: d.property?.longitude, asset_type: d.asset_type, buyer: b?.display_name, buyer_entity_id: b?.entity_id, seller: s?.display_name, seller_entity_id: s?.entity_id, sale_price: d.sale_price, units: d.units, sqft: d.sqft, ppu: d.ppu, ppsf: d.ppsf, confidence: d.confidence, parse_status: d.parse_status, source_url: d.source_url, source_system: d.source_system }; }
function filterDeals(rows: Row[], q: URLSearchParams) { const text = (q.get("q") || "").toLowerCase(), pmin = money(q.get("price_min")), pmax = money(q.get("price_max")); return rows.map(dealOut).filter((d) => (!text || `${d.address || ""} ${d.buyer || ""} ${d.seller || ""}`.toLowerCase().includes(text)) && (!q.get("borough") || d.borough === q.get("borough")) && (!q.get("asset_type") || d.asset_type === q.get("asset_type")) && (!q.get("market") || d.market === q.get("market")) && (pmin === null || Number(d.sale_price || 0) >= pmin) && (pmax === null || Number(d.sale_price || 0) <= pmax) && (!q.get("status") || d.parse_status === q.get("status")) && (q.get("has_buyer") !== "true" || !!d.buyer)); }
function buyers(data: Awaited<ReturnType<typeof load>>, f: Row = {}) { const m = new Map<string, Row>(); for (const d of data.deals) { if (f.asset_type && d.asset_type !== f.asset_type) continue; if (f.borough && d.property?.borough !== f.borough) continue; for (const b of d.buyers || []) { const r = m.get(b.entity_id) || { entity_id: b.entity_id, name: b.display_name, is_spv_suspect: b.is_spv_suspect, n: 0, vol: 0, last_deal: null, types: new Set(), boroughs: new Set() }; r.n += 1; r.vol += Number(d.sale_price || 0); r.last_deal = !r.last_deal || String(d.sale_date || "") > String(r.last_deal || "") ? d.sale_date : r.last_deal; if (d.asset_type) r.types.add(d.asset_type); if (d.property?.borough) r.boroughs.add(d.property.borough); m.set(b.entity_id, r); } } return Array.from(m.values()).map((r) => ({ ...r, deal_count: r.n, volume: r.vol, types: Array.from(r.types), boroughs: Array.from(r.boroughs), contact_count: (data.contactsByEntity.get(r.entity_id) || []).length, has_contact: (data.contactsByEntity.get(r.entity_id) || []).length > 0 })); }
function leaderboards(data: Awaited<ReturnType<typeof load>>, groupBy = "asset_type", top = 5, rankBy = "count") { const groups = new Map<string, Row[]>(); for (const d of data.deals) { const grp = groupBy === "borough" ? d.property?.borough : d.asset_type; if (!grp) continue; for (const b of d.buyers || []) { if (!groups.has(grp)) groups.set(grp, []); groups.get(grp)!.push({ entity_id: b.entity_id, name: b.display_name, sale_price: d.sale_price }); } } const out: Row[] = []; for (const [grp, arr] of groups) { const m = new Map<string, Row>(); for (const r of arr) { const x = m.get(r.entity_id) || { grp, name: r.name, n: 0, vol: 0 }; x.n++; x.vol += Number(r.sale_price || 0); m.set(r.entity_id, x); } Array.from(m.values()).sort((a, b) => rankBy === "vol" ? (b.vol - a.vol || b.n - a.n) : (b.n - a.n || b.vol - a.vol)).slice(0, top).forEach((r, i) => out.push({ ...r, rk: i + 1 })); } return out; }
function propertyMap(data: Awaited<ReturnType<typeof load>>, lim = 1000) { return { points: [], count: 0, note: "No geocoded latitude/longitude rows are available in the canonical CSV fallback." }; }
async function handle(req: Request) { const p = pathOf(req), q = qs(req), data = await load(); if (p === "/api/health") return json({ status: "ok", runtime: "netlify-core-routes", schema: data.source, deals: data.deals.length }); if (p === "/api/meta") { const prices = data.deals.map((d: Row) => Number(d.sale_price || 0)).filter(Boolean), dates = data.deals.map((d: Row) => d.sale_date).filter(Boolean).sort(); return json({ asset_types: Array.from(new Set(data.deals.map((d: Row) => d.asset_type).filter(Boolean))).sort(), boroughs: Array.from(new Set(data.properties.map((p: Row) => p.borough).filter(Boolean))).sort(), stats: { deals: data.deals.length, priced: prices.length, total_volume: prices.reduce((s, n) => s + n, 0), earliest: dates[0] || null, latest: dates.at(-1) || null, unique_buyers: buyers(data).length, contacts: data.contacts.length, open_reviews: data.reviews.length } }); } if (p === "/api/deals") { const page = Math.max(1, Number(q.get("page") || 1)), per = Math.min(200, Math.max(1, Number(q.get("per_page") || 50))); const rows = filterDeals(data.deals, q).sort((a, b) => String(b.sale_date || "").localeCompare(String(a.sale_date || ""))); return json({ total: rows.length, page, per_page: per, pulse: { n: rows.length, vol: rows.reduce((s, d) => s + Number(d.sale_price || 0), 0), median: null }, deals: rows.slice((page - 1) * per, page * per) }); } if (p === "/api/buyers") return json({ buyers: buyers(data, { borough: q.get("borough"), asset_type: q.get("asset_type") }).sort((a, b) => b.n - a.n || b.vol - a.vol).slice(0, Number(q.get("limit") || 60)) }); if (p === "/api/leaderboards") return json({ boards: leaderboards(data, q.get("group_by") || "asset_type", Number(q.get("top") || 5), q.get("rank_by") || "count") }); if (p === "/api/property-map") return json(propertyMap(data, Number(q.get("limit") || 1000))); if (p.startsWith("/api/entities/")) { const id = decodeURIComponent(p.split("/").pop() || ""); const e = data.ent.get(id); if (!e) return json({ error: "not found" }, 404); return json({ entity: e, contacts: data.contactsByEntity.get(id) || [], deals: data.deals.filter((d: Row) => (d.parties || []).some((x: Row) => x.entity_id === id)).map(dealOut) }); } if (p === "/api/review/act" && req.method === "POST") { try { const b = await req.json(); const status = b.action === "resolve" || b.action === "confirm_merge" ? "resolved" : "dismissed"; await patch(`${T.review}?review_id=eq.${encodeURIComponent(b.review_id)}`, { status, resolved_by: b.user_id || "broker", resolved_at: new Date().toISOString() }); return json({ status }); } catch { return json({ status: "not_persisted", note: "Review action could not be persisted because Supabase REST key is unavailable." }); } } if (p === "/api/review") return json({ items: data.reviews, open_counts: data.reviews.reduce((o: Row, r: Row) => { o[r.issue_class] = (o[r.issue_class] || 0) + 1; return o; }, {}) }); return json({ error: "not found", path: p }, 404); }
export default async (req: Request) => { try { return await handle(req); } catch (e: any) { return json({ error: e?.message || String(e) }, 500); } };
export const config: Config = { path: ["/api/health", "/api/meta", "/api/deals", "/api/buyers", "/api/leaderboards", "/api/property-map", "/api/entities/*", "/api/review", "/api/review/act"] };
