import type { Config } from "@netlify/functions";

type Row = Record<string, any>;
const RAW_CSV = "https://raw.githubusercontent.com/rubbik26-commits/buyerDB/ACRIS/skyline/NEW_YORK_CLOSED_ENRICHED_v8.csv";
const VALID_BOROUGHS = new Set(["Manhattan", "Brooklyn", "Queens", "Bronx", "Staten Island"]);
const env = (name: string) => (globalThis as any).Netlify?.env?.get?.(name) || "";
const json = (data: unknown, status = 200) => new Response(JSON.stringify(data, null, 2), { status, headers: { "content-type": "application/json" } });
const pathOf = (req: Request) => new URL(req.url).pathname.replace(/\/$/, "") || "/";
const params = (req: Request) => new URL(req.url).searchParams;
const money = (v: unknown) => { if (v === null || v === undefined || v === "") return null; const n = Number(String(v).replace(/[$,\s]/g, "")); return Number.isFinite(n) ? n : null; };
const norm = (s: unknown) => String(s || "").trim().toUpperCase().replace(/[^A-Z0-9]+/g, " ").replace(/\s+/g, " ").trim();
const safeId = (prefix: string, s: unknown) => `${prefix}-${norm(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "unknown"}`;
const T = { deals: "sbi_deals", properties: "sbi_properties", parties: "sbi_deal_parties", entities: "sbi_entities", contacts: "sbi_contacts", interactions: "sbi_interactions", review: "sbi_review_queue", runs: "sbi_source_runs", uploads: "sbi_uploads", uploadRows: "sbi_upload_rows" };
function cfg() { const raw = env("SUPABASE_URL") || env("VITE_SUPABASE_URL") || env("VITE_API_URL"); const key = env("SUPABASE_SERVICE_ROLE_KEY") || env("SUPABASE_SERVICE_KEY") || env("SUPABASE_PUBLISHABLE_KEY") || env("VITE_SUPABASE_ANON_KEY"); if (!raw || !key) throw new Error("Supabase URL/key env vars are missing."); return { url: new URL(raw).origin, key }; }
async function rest(route: string, init: RequestInit = {}) { const c = cfg(); const headers = new Headers(init.headers || {}); headers.set("apikey", c.key); headers.set("authorization", `Bearer ${c.key}`); if (init.body && !headers.has("content-type")) headers.set("content-type", "application/json"); const r = await fetch(`${c.url}/rest/v1/${route}`, { ...init, headers }); if (!r.ok) throw new Error(`${route} ${r.status}: ${(await r.text()).slice(0, 500)}`); return r.status === 204 ? null : r.json(); }
const sel = (table: string, query = "select=*") => rest(`${table}?${query}`);
const maybe = async (table: string, query = "select=*") => { try { return await sel(table, query); } catch { return []; } };
const rpc = (fn: string, body: unknown = {}) => rest(`rpc/${fn}`, { method: "POST", body: JSON.stringify(body) });

function parseCsv(text: string): Row[] { const rows: string[][] = []; let row: string[] = [], cur = "", q = false; for (let i = 0; i < text.length; i++) { const ch = text[i], next = text[i + 1]; if (q) { if (ch === '"' && next === '"') { cur += '"'; i++; } else if (ch === '"') q = false; else cur += ch; } else if (ch === '"') q = true; else if (ch === ",") { row.push(cur); cur = ""; } else if (ch === "\n") { row.push(cur); rows.push(row); row = []; cur = ""; } else if (ch !== "\r") cur += ch; } if (cur || row.length) { row.push(cur); rows.push(row); } const headers = (rows.shift() || []).map((h) => h.trim()); return rows.filter((r) => r.some(Boolean)).map((r) => Object.fromEntries(headers.map((h, i) => [h, r[i] || ""]))); }
function srcSystem(url: string) { const u = String(url || "").toLowerCase(); if (u.includes("a836-acris")) return "acris"; if (u.includes("traded.co")) return "traded"; if (u.includes("crexi")) return "crexi"; if (u.includes("instagram")) return "instagram"; return "csv"; }
async function loadCsv() { const res = await fetch(RAW_CSV, { headers: { "user-agent": "buyerdb-workflow-fallback" } }); if (!res.ok) throw new Error(`CSV fallback fetch failed ${res.status}`); const csvRows = parseCsv(await res.text()).filter((r) => VALID_BOROUGHS.has(String(r.Borough || ""))); const ent = new Map<string, Row>(); const properties: Row[] = [], deals: Row[] = [], parties: Row[] = [], reviews: Row[] = []; const contacts: Row[] = [], runs: Row[] = [], uploads: Row[] = [], contactsByEntity = new Map<string, Row[]>(); const propSeen = new Set<string>(); const addEnt = (name: string) => { if (!name || !String(name).trim()) return null; const entity_id = safeId("ent", name); if (!ent.has(entity_id)) ent.set(entity_id, { entity_id, display_name: String(name).trim(), entity_type: /\bLLC\b/i.test(name) ? "llc" : "unknown", is_spv_suspect: false }); return ent.get(entity_id)!; };
  csvRows.forEach((r, i) => { const address = String(r.Address || "").trim(), borough = String(r.Borough || "").trim(); if (!address || !borough) return; const property_id = safeId("prop", `${address}-${borough}`); if (!propSeen.has(property_id)) { propSeen.add(property_id); properties.push({ property_id, address_raw: address, borough, market: r.Market || null, bbl: null }); } const buyer = addEnt(r.Buyer), seller = addEnt(r.Seller); const d: Row = { deal_id: safeId("deal", r.Shortcode || `${address}-${r["Sale Price"]}-${r.sale_date_iso || r["Sale Date"]}-${i}`), property_id, sale_date: r.sale_date_iso || r["Sale Date"] || null, post_date: r["Post Date"] || null, asset_type: r["Asset Type"] || null, sale_price: money(r["Sale Price"]), units: money(r.Units), sqft: money(r["Sq Ft"]), ppu: money(r.PPU), ppsf: money(r.PPSF), source_system: srcSystem(r["Source URL"]), source_url: r["Source URL"] || null, shortcode: r.Shortcode || null, confidence: money(r.Confidence), parse_status: r["Parse Status"] || "ok", notes: r.Notes || null, property: properties.find((p) => p.property_id === property_id) || {}, buyers: buyer ? [buyer] : [], sellers: seller ? [seller] : [] }; deals.push(d); if (buyer) parties.push({ deal_id: d.deal_id, entity_id: buyer.entity_id, role: "buyer" }); if (seller) parties.push({ deal_id: d.deal_id, entity_id: seller.entity_id, role: "seller" }); if (d.parse_status === "needs_review") reviews.push({ review_id: `csv-review-${d.deal_id}`, object_type: "deal", object_id: d.deal_id, issue_class: "legacy_needs_review", severity: "normal", payload: { address, notes: d.notes }, status: "open" }); });
  return { deals, properties, parties, entities: Array.from(ent.values()), contacts, reviews, runs, uploads, contactsByEntity, source: "csv-fallback" }; }
async function loadSupa() { const [deals, props, parties, ents, contacts, reviews, runs, uploads] = await Promise.all([sel(T.deals, "select=*&order=sale_date.desc.nullslast&limit=5000"), sel(T.properties, "select=*&limit=5000"), sel(T.parties, "select=*&limit=12000"), sel(T.entities, "select=*&limit=12000"), maybe(T.contacts, "select=*&limit=12000"), maybe(T.review, "select=*&status=eq.open&order=created_at.desc&limit=1000"), maybe(T.runs, "select=*&order=started_at.desc&limit=200"), maybe(T.uploads, "select=*&order=created_at.desc&limit=100")]); const prop = new Map(props.map((p: Row) => [p.property_id, p])); const ent = new Map(ents.map((e: Row) => [e.entity_id, e])); const contactsByEntity = new Map<string, Row[]>(); for (const c of contacts) { if (!contactsByEntity.has(c.entity_id)) contactsByEntity.set(c.entity_id, []); contactsByEntity.get(c.entity_id)!.push(c); } const byDeal = new Map<string, Row[]>(); for (const p of parties) { if (!byDeal.has(p.deal_id)) byDeal.set(p.deal_id, []); byDeal.get(p.deal_id)!.push(p); } const rows = deals.map((d: Row) => { const ps = byDeal.get(d.deal_id) || []; return { ...d, property: prop.get(d.property_id) || {}, parties: ps, buyers: ps.filter((x) => x.role === "buyer").map((x) => ent.get(x.entity_id)).filter(Boolean), sellers: ps.filter((x) => x.role === "seller").map((x) => ent.get(x.entity_id)).filter(Boolean) }; }); return { deals: rows, properties: props, parties, entities: ents, contacts, reviews, runs, uploads, contactsByEntity, source: "supabase" }; }
async function load() { try { const data = await loadSupa(); if (data.deals.length) return data; return await loadCsv(); } catch { return await loadCsv(); } }
function activeBuyers(data: Awaited<ReturnType<typeof load>>) { const m = new Map<string, Row>(); for (const d of data.deals) for (const b of d.buyers || []) { const r = m.get(b.entity_id) || { entity_id: b.entity_id, name: b.display_name, deal_count: 0, volume: 0, last_deal: null }; r.deal_count++; r.volume += Number(d.sale_price || 0); r.last_deal = !r.last_deal || String(d.sale_date || "") > String(r.last_deal || "") ? d.sale_date : r.last_deal; m.set(b.entity_id, r); } return Array.from(m.values()).map((r) => ({ ...r, n: r.deal_count, vol: r.volume, contact_count: (data.contactsByEntity.get(r.entity_id) || []).length, has_contact: (data.contactsByEntity.get(r.entity_id) || []).length > 0 })).sort((a, b) => b.volume - a.volume || b.deal_count - a.deal_count); }
function latestOwners(data: Awaited<ReturnType<typeof load>>) { const m = new Map<string, Row>(); for (const d of data.deals) { const old = m.get(d.property_id); if (old && String(old.sale_date || "") >= String(d.sale_date || "")) continue; const owner = (d.buyers || [])[0], seller = (d.sellers || [])[0]; m.set(d.property_id, { property_id: d.property_id, deal_id: d.deal_id, address: d.property?.address_raw, borough: d.property?.borough, market: d.property?.market, bbl: d.property?.bbl, sale_date: d.sale_date, sale_price: d.sale_price, asset_type: d.asset_type, owner_entity_id: owner?.entity_id, current_owner: owner?.display_name, known_owner: owner?.display_name, seller: seller?.display_name, has_contact: owner ? (data.contactsByEntity.get(owner.entity_id) || []).length > 0 : false }); } return Array.from(m.values()).sort((a, b) => Number(b.sale_price || 0) - Number(a.sale_price || 0)); }
async function workbench() { const data = await load(); const buyers = activeBuyers(data); const gaps = buyers.filter((b) => b.deal_count >= 2 && !b.has_contact).slice(0, 12); return json({ stats: { deals: data.deals.length, priced_deals: data.deals.filter((d) => d.sale_price !== null).length, total_volume: data.deals.reduce((s, d) => s + Number(d.sale_price || 0), 0), unique_buyers: buyers.length, unique_sellers: new Set(data.parties.filter((p) => p.role === "seller").map((p) => p.entity_id)).size, contacts: data.contacts.length, contact_gaps: gaps.length, open_reviews: data.reviews.length }, contact_gaps: gaps, owner_targets: latestOwners(data).slice(0, 12), review_items: data.reviews.slice(0, 12), scrape_runs: data.runs.slice(0, 12), source: data.source }); }
async function properties(req: Request) { const q = params(req), data = await load(); const text = (q.get("q") || "").toLowerCase(), page = Math.max(1, Number(q.get("page") || 1)), per = Math.min(200, Math.max(1, Number(q.get("per_page") || 50))); const rows = latestOwners(data).filter((p) => (!q.get("borough") || p.borough === q.get("borough")) && (!q.get("asset_type") || p.asset_type === q.get("asset_type")) && (q.get("contact_gap") !== "true" || !p.has_contact) && (!text || `${p.address || ""} ${p.bbl || ""} ${p.current_owner || ""} ${p.seller || ""}`.toLowerCase().includes(text))); return json({ total: rows.length, page, per_page: per, properties: rows.slice((page - 1) * per, page * per) }); }
async function tasks(req: Request) { const lim = Math.min(250, Number(params(req).get("limit") || 100)); const data = await load(); const out = activeBuyers(data).filter((b) => b.deal_count >= 2 && !b.has_contact).slice(0, lim).map((b) => ({ kind: "contact_gap", priority: b.volume >= 25000000 ? "high" : "normal", entity_id: b.entity_id, title: `Find phone/email for ${b.name}`, detail: `${b.deal_count} buyer deals`, metric: b.volume })); for (const r of data.reviews.slice(0, lim)) out.push({ kind: "review", priority: r.severity || "normal", review_id: r.review_id, title: `Review ${r.issue_class}`, detail: `${r.object_type} - ${r.object_id}`, metric: null }); return json({ tasks: out.slice(0, lim) }); }
async function interaction(req: Request) { try { const b = await req.json(); return json(await rpc("api_log_interaction", { entity_id: b.entity_id, user_id: b.user_id || "broker", channel: b.channel || "other", subject: b.subject || null, notes: b.notes || null, outcome: b.outcome || null })); } catch { return json({ interaction: null, status: "not_persisted" }); } }
async function runs(req: Request) { if (req.method === "POST") { try { const b = await req.json(); return json(await rpc("api_request_scrape", { job: b.job || "full_refresh", user_id: b.user_id || "broker", options: b.options || {} })); } catch { return json({ status: "not_persisted", note: "Scraper request could not be persisted because Supabase REST key is unavailable." }); } } return json({ runs: await maybe(T.runs, "select=*&order=started_at.desc&limit=75") }); }
async function fixStaleRuns() { try { return json(await rpc("api_fix_stale_runs", {})); } catch { return json({ fixed: [], count: 0, status: "not_persisted" }); } }
async function audit() { const data = await load(); return json({ totals: { properties: data.properties.length, deals: data.deals.length, entities: data.entities.length, contacts: data.contacts.length, uploads: data.uploads.length, open_reviews: data.reviews.length, failed_scrapes: data.runs.filter((r) => ["failed", "timeout", "quota_blocked", "completed_with_errors"].includes(r.status)).length }, duplicate_properties: [], duplicate_deals: [], missing_parties: data.deals.filter((d) => !(d.buyers || []).length || !(d.sellers || []).length).slice(0, 50), contact_gaps: activeBuyers(data).filter((b) => b.deal_count >= 2 && !b.has_contact).slice(0, 50), problem_runs: data.runs.filter((r) => ["running", "failed", "timeout", "quota_blocked", "completed_with_errors"].includes(r.status)).slice(0, 50), problem_uploads: data.uploads.filter((u) => ["failed", "resolving", "staged"].includes(u.status)).slice(0, 50), source: data.source }); }
export default async (req: Request) => { try { const p = pathOf(req); if (p === "/api/workbench") return workbench(); if (p === "/api/properties") return properties(req); if (p === "/api/tasks") return tasks(req); if (p === "/api/interactions" && req.method === "POST") return interaction(req); if (p === "/api/scrapers/runs") return runs(req); if (p === "/api/scrapers/request") return runs(req); if (p === "/api/admin/audit") return audit(); if (p === "/api/admin/fix-stale-runs") return fixStaleRuns(); if (p.startsWith("/api/outreach")) { const data = await load(); return json({ targets: activeBuyers(data).slice(0, 75) }); } if (p.startsWith("/api/uploads")) { if (req.method === "GET") return json({ uploads: await maybe(T.uploads, "select=*&order=created_at.desc&limit=50") }); return json({ stats: { contacts_created: 0, interactions_created: 0, new_entity: 0, auto_matched: 0, needs_review: 0, skipped_no_name: 0 }, status: "staged_not_persisted" }); } if (p.startsWith("/api/saved-views")) return json({ views: [] }); return json({ error: "not found", path: p }, 404); } catch (e: any) { return json({ error: e?.message || String(e) }, 500); } };
export const config: Config = { path: ["/api/workbench", "/api/properties", "/api/tasks", "/api/interactions", "/api/scrapers/runs", "/api/scrapers/request", "/api/admin/audit", "/api/admin/fix-stale-runs", "/api/outreach/*", "/api/saved-views/*", "/api/uploads/*"] };
